openapi: 3.0.0
info:
  title: RAG Chatbot API
  version: 1.0.0
  description: API for the Retrieval-Augmented Generation (RAG) Chatbot backend,
    serving book content-based queries.

servers:
  - url: /api/v1
    description: Base URL for RAG Chatbot API

paths:
  /embed:
    post:
      summary: Generate embeddings for book content chunks
      description: Takes raw text content and returns its vector embedding.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
                  description: The book content chunk to embed.
                source_url:
                  type: string
                  description: URL of the content source (Docusaurus page).
                chapter_title:
                  type: string
                  description: Title of the chapter.
                position:
                  type: string
                  description: Positional data within the source.
      responses:
        '200':
          description: Embedding successfully generated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  embedding:
                    type: array
                    items:
                      type: number
                    description: The vector embedding.
                  chunk_id:
                    type: string
                    description: ID of the content chunk.
        '400':
          description: Invalid input.

  /store:
    post:
      summary: Store embedded content in Qdrant
      description: Takes an embedding and associated metadata and stores it in the vector database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chunk_id
                - embedding
                - metadata
              properties:
                chunk_id:
                  type: string
                  description: ID of the content chunk.
                embedding:
                  type: array
                  items:
                    type: number
                  description: The vector embedding.
                metadata:
                  type: object
                  description: Associated metadata (source_url, chapter_title, position).
      responses:
        '200':
          description: Content successfully stored.
        '400':
          description: Invalid input.

  /query:
    post:
      summary: Query Qdrant for relevant content
      description: Takes a user query, embeds it, and retrieves relevant content chunks from Qdrant.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_query
              properties:
                user_query:
                  type: string
                  description: The user's natural language query.
                context_text_selected:
                  type: string
                  nullable: true
                  description: Optional user-selected text for additional context.
      responses:
        '200':
          description: Retrieved relevant content chunks.
          content:
            application/json:
              schema:
                type: object
                properties:
                  retrieved_chunks:
                    type: array
                    items:
                      type: object
                      properties:
                        chunk_id:
                          type: string
                        text:
                          type: string
                        source_url:
                          type: string
                        score:
                          type: number
                    description: List of relevant content chunks.
        '400':
          description: Invalid input.

  /chat:
    post:
      summary: Get chatbot response from LLM
      description: Takes a user query and retrieved content to generate a grounded response using an LLM.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_query
                - retrieved_content
              properties:
                user_query:
                  type: string
                  description: The user's natural language query.
                retrieved_content:
                  type: array
                  items:
                    type: object
                    properties:
                      chunk_id:
                        type: string
                      text:
                        type: string
                  description: List of relevant content chunks retrieved from Qdrant.
                user_session_id:
                  type: string
                  description: Identifier for the user's chat session.
      responses:
        '200':
          description: Chatbot response generated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response_text:
                    type: string
                    description: The generated chatbot response.
                  grounded_sources:
                    type: array
                    items:
                      type: object
                      properties:
                        chunk_id:
                          type: string
                        source_url:
                          type: string
                    description: Sources from the book content used to ground the response.
        '400':
          description: Invalid input.
